### ISSUE TITLE
servers hard coded in config 

### ISSUE THREAD

**Issue by gedw99** [mdawar/nats-dashboard#1]
at the moment its set in the TypeScript config.

``` 
export const serversList: { name: string; url: string }[] = [
  {
    name: 'localhost',
    url: 'http://localhost:8222',
  },
  {
    name: 'demo.nats.io',
    url: 'https://demo.nats.io:8222',
  },
];
```

what do you think about allowing NATS server URLS to be added via the Web GUI, and then saved as a list on the server ?

**Comment by mdawar** [comment]
You're right about this, I was thinking about using a environment variable on build to allow anyone building the app to customize the servers list.

Also there are no servers for this app, we can only store on the client, for example using local storage.

So what do you think?

**Comment by gedw99** [comment]
How about just keeping it simple for now and just change the GUI so that a user can input any NATS Url OR pick from the existing hard coded ones. 

If the user puts in a new URL, then store it in memory.

Later, stuff like a backend or some persistence might make sense.

How's this sound ?

**Comment by mdawar** [comment]
Sorry if it's not obvious, but you can already do that, there's an input at the top of the page where you can type the URL or choose from the servers list, but you need to stop monitoring to change the URL if it's already active.

I will make sure to change the input placeholder to make it clear that you can type a URL.

This app is just a simple tool like [nats-top](https://github.com/nats-io/nats-top) but for the browser, so I'd like to keep it simple, adding persistence and a backend would over-complicate the app and I think there are better solutions, like using a Prometheus exporter with Grafana to build a custom dashboard with persistence.

**Comment by danielrosa-zh** [comment]
Hi @mdawar ,
I think an environment variable to customize the servers list sounds good. Do you have a plan to add that ?
Thanks in advance

**Comment by mdawar** [comment]
Hey @danielrosa-zh,
Yes we can add an environment variable, but the only way I can think of is a comma separated list of server URLs, do you have a better idea?

**Comment by danielrosa-zh** [comment]
@mdawar 
comma separated should works, thank you!

**Comment by mdawar** [comment]
The environment variable `PUBLIC_SERVERS_LIST` was added in the latest version `v0.2.11` (The prefix `PUBLIC_` is needed to make the variable available on the client side).

The value should be a comma separated list of server URLs:

```sh
PUBLIC_SERVERS_LIST="http://localhost:8222,https://demo.nats.io:8222" npm run build
```

This list will be used for the quick access buttons and for the URL input element suggestions.
