### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by BaptisteMoureaux** [mdawar/nats-dashboard#11]
Is there a specific reason on why there is not a logs tab in the dashboard ? I might try to contribute if it's possible !

**Comment by mdawar** [comment]
This dashboard only displays the information exposed by the HTTP monitoring server of NATS, and no logs are exposed by this server.

You can find the exposed info documented at: https://docs.nats.io/running-a-nats-service/nats_admin/monitoring

**Comment by BaptisteMoureaux** [comment]
Got it ! I don't know why but for some reason I thought you were listening through nats directly 🤦, thank you for the work.
