### ISSUE TITLE
release a binary is possible ?

### ISSUE THREAD

**Issue by gedw99** [mdawar/nats-dashboard#2]
Is it possible to release a binary as part of the tagged releases ?

**Comment by gedw99** [comment]
Just realised that there are a few files released. So maybe then a tar can be the release ?

**Comment by gedw99** [comment]
Then people can reuse it like here: https://github.com/maxpert/marmot-pocketbase-flyio/blob/main/Dockerfile

That's running a NATS Server that is embedded BTW.

But you can see how the docker build phase just pulls a gzipped tar, so that when it boots on fly.io it can be run.

**Comment by mdawar** [comment]
Yeah maybe we can add the built app files as a zip file to the releases, but as a binary I don't think so, there's already a Docker image that you can use:

```sh
docker run --rm -it -p 8000:80 mdawar/nats-dashboard
```

**Comment by gedw99** [comment]
yeah can’t use the docker as I need to inject the dust into another docker.

So , that’s why I suggested  just add a GitHub workflow that is a bit like the cloud fake one but releases the dost as a zip zip or tar . 

Is that cool ?

**Comment by mdawar** [comment]
I've already made this change, check out the latest release [v0.2.9](https://github.com/mdawar/nats-dashboard/releases/tag/v0.2.9) which contains the build files.
