### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by 18600294832** [mdawar/nats-dashboard#8]
Server Information

Cannot fetch the server information.

http://xxxx:8222/varz
this request status is 200
but cors error 
not found any result data

**Comment by mdawar** [comment]
NATS server versions prior to [v2.9.22](https://github.com/nats-io/nats-server/releases/tag/v2.9.22) do not support CORS requests, but you can enable JSONP requests from the settings (Click on the top right gear icon).

If this does not resolve your problem please provide more details.

**Comment by 18600294832** [comment]
thanks. problem solved

**Comment by 18600294832** [comment]
problem solved
